#我的一些参数配置读取测试
student:
  name: 高子宁
  age: 23
age1: 10
link: "<br> 连接：${student.name}  ,  ${student.age}"

#tomcat配置
server:
  port: 8080
#  servlet:
#    context-path: /hello

#热部署开启、jsp配置
spring:
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#数据库配置
  datasource:
    url: jdbc:mysql://192.168.127.129:3306/ning?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mapper/*.xml



